name: 'Terraform'

on:
  #  workflow_dispatch:
  #    inputs:
  #      apps:
  #        description: 'Actions to perform for the GKE Cluster'
  #        type: string
  #        default: '["create-GKE-Cluster", "destroy-GKE-Cluster"]'
  #        required: true  
  push:
    branches:
      - "main"              # Match the main branch
      - "feature/**"        # Match any branch that starts with 'feature'
  pull_request:
    branches:
      - "main"              # Match pull requests targeting the main branch
      - "feature/**"        # Match any pull request targeting branches that start with 'feature'
  
  #env:
  #  apps: ${{ github.event_name == 'push' && '["create-GKE-Cluster", "destroy-GKE-Cluster"]' || inputs.apps}} # https://docs.github.com/en/actions/learn-github-actions/expressions#example

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-jobs
  cancel-in-progress: true

jobs:
  # pick-your-choice:
  #   runs-on: ububtu-latest
  #   steps:
  #    - shell: pwsh
  #       run: |
  #         echo 'apps from input ${{ inputs.apps }}'
  #         echo 'apps from env ${{ env.apps }}'

  # oidc_debug_test:
  #   permissions:
  #     contents: read
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   name: A test of the oidc debugger
  #   steps:
  #     - name: Checkout actions-oidc-debugger
  #       uses: actions/checkout@v3
  #       with:
  #         repository: github/actions-oidc-debugger
  #         ref: main
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         path: ./.github/actions/actions-oidc-debugger
  #     - name: Debug OIDC Claims
  #       uses: ./.github/actions/actions-oidc-debugger
  #       with:
  #         audience: '${{ github.server_url }}/${{ github.repository_owner }}'

  gke-deploy:
    name: 'GKE Deploy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2.0.0
        with:
          workload_identity_provider: 'projects/175415323680/locations/global/workloadIdentityPools/githubpool/providers/github'
          service_account: github-wif-sa@properties-app-418208.iam.gserviceaccount.com

      - name: Setup Terraform for GKE
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # - name: Terraform Init for GKE
      #   run: |
      #     echo "Initializing Terraform..."
      #     terraform init
      #     echo "Terraform initialized successfully."

      # - name: Terraform Plan for GKE
      #   run: |
      #       echo "Generating Terraform plan..."
      #       terraform plan -var-file="dev.tfvars" -input=false
      #       echo "Terraform plan generated."

      # - name: Terraform Apply for GKE
      #   run: |
      #       echo "Applying Terraform changes..."
      #       terraform apply -auto-approve -var-file="dev.tfvars" -input=false
      #       echo "Terraform changes applied successfully."

      # - name: Display Terraform Outputs for GKE
      #   run: |
      #       echo "Displaying Terraform outputs..."
      #       echo "CA Certificate: $(terraform output -raw ca_certificate)"
      #       echo "Cluster ID: $(terraform output -raw cluster_id)"
      #       echo "DNS Cache Enabled: $(terraform output -raw dns_cache_enabled)"
      #       echo "Cluster Endpoint: $(terraform output -raw endpoint)"
      #       echo "Fleet Membership: $(terraform output -raw fleet_membership)"
      #       echo "Gateway API Channel: $(terraform output -raw gateway_api_channel)"
      #       echo "Horizontal Pod Autoscaling Enabled: $(terraform output -raw horizontal_pod_autoscaling_enabled)"
      #       echo "HTTP Load Balancing Enabled: $(terraform output -raw http_load_balancing_enabled)"
      #       echo "Identity Namespace: $(terraform output -raw identity_namespace)"
      #       echo "Identity Service Enabled: $(terraform output -raw identity_service_enabled)"
      #       echo "Instance Group URLs: $(terraform output -json instance_group_urls)"
      #       echo "Intra-node Visibility Enabled: $(terraform output -raw intranode_visibility_enabled)"
      #       echo "Location: $(terraform output -raw location)"
      #       echo "Logging Service: $(terraform output -raw logging_service)"
      #       echo "Master Authorized Networks Config: $(terraform output -json master_authorized_networks_config)"
      #       echo "Master Version: $(terraform output -raw master_version)"
      #       echo "Mesh Certificates Config: $(terraform output -json mesh_certificates_config)"
      #       echo "Min Master Version: $(terraform output -raw min_master_version)"
      #       echo "Monitoring Service: $(terraform output -raw monitoring_service)"
      #       echo "Cluster Name: $(terraform output -raw name)"
      #       echo "Network Policy Enabled: $(terraform output -raw network_policy_enabled)"
      #       echo "Node Pools Names: $(terraform output -json node_pools_names)"
      #       echo "Node Pools Versions: $(terraform output -json node_pools_versions)"
      #       echo "Region: $(terraform output -raw region)"
      #       echo "Release Channel: $(terraform output -raw release_channel)"
      #       echo "Service Account: $(terraform output -raw service_account)"
      #       echo "TPU IPv4 CIDR Block: $(terraform output -raw tpu_ipv4_cidr_block)"
      #       echo "Cluster Type: $(terraform output -raw type)"
      #       echo "Vertical Pod Autoscaling Enabled: $(terraform output -raw vertical_pod_autoscaling_enabled)"
      #       echo "Zones: $(terraform output -json zones)"
      #       echo "Terraform outputs displayed successfully."


      - name: Terraform Plan Destroy
        run: |
          echo "Generating Terraform destroy plan..."
          terraform plan -var-file="dev.tfvars" -input=false -destroy -input=false
          echo "Terraform destroy plan generated."

      - name: Terraform Destroy
        run: |
         echo "Destroying Terraform resources..."
         terraform destroy  -var-file="dev.tfvars" -auto-approve -input=false
         echo "Terraform resources destroyed successfully."
